name: flutter_application_2
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  firebase_core: ^2.27.0
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # The 'assets:' and 'fonts:' sections related to NotoSansSymbols-Regular.ttf
  # are completely removed here.