# PlateShare Queries

query ListAvailableDonations @auth(level: PUBLIC) {
  donations(where: { status: { eq: "available" } }) {
    id
    name
    phone
    address
    source
    quantity
    ngo
    imageUrls
    status
    donor {
      name
    }
    createdAt
  }
}

query GetDonationById($id: UUID!) @auth(level: PUBLIC) {
  donation(id: $id) {
    id
    name
    phone
    address
    source
    quantity
    ngo
    imageUrls
    status
    donor {
      name
      phone
      address
    }
    createdAt
  }
}

query ListUserDonations @auth(level: USER) {
  donations(where: { donorId: { eq_expr: "auth.uid" } }) {
    id
    name
    source
    quantity
    status
    createdAt
  }
}

query ListUserRequests @auth(level: USER) {
  foodRequests(where: { recipientId: { eq_expr: "auth.uid" } }) {
    id
    status
    requestTime
    donation {
      name
      source
      quantity
      donor {
        name
      }
    }
  }
}

query ListPendingRequests @auth(level: USER) {
  foodRequests(where: { status: { eq: "pending" } }) {
    id
    status
    requestTime
    donation {
      name
      source
      quantity
      donor {
        name
        phone
        address
      }
    }
    recipient {
      name
      phone
      address
    }
  }
}
      releaseYear
      description
    }
    reviews: reviews_on_movie {
      reviewText
      reviewDate
      rating
      user {
        id
        username
      }
    }
  }
}

# Search for movies, actors, and reviews
query SearchMovie($titleInput: String, $genre: String) @auth(level: PUBLIC, insecureReason: "Anyone can search for movies.") {
  movies(
    where: {
      _and: [{ genre: { eq: $genre } }, { title: { contains: $titleInput } }]
    }
  ) {
    id
    title
    genre
    imageUrl
  }
}
