# PlateShare App Schema

type Donor @table {
  id: String! @default(expr: "auth.uid")
  name: String!
  phone: String!
  address: String!
  email: String
}

type Donation @table {
  id: UUID! @default(expr: "uuidV4()")
  name: String!
  phone: String!
  address: String!
  source: String!
  quantity: String!
  ngo: String!
  imageUrls: [String!]!
  status: String! @default(value: "available")
  donor: Donor!
  createdAt: Timestamp! @default(expr: "request.time")
}

type Recipient @table {
  id: String! @default(expr: "auth.uid")
  name: String!
  phone: String!
  address: String!
  email: String
}

type FoodRequest @table {
  id: UUID! @default(expr: "uuidV4()")
  donation: Donation!
  recipient: Recipient!
  status: String! @default(value: "pending")
  requestTime: Timestamp! @default(expr: "request.time")
}
  reviewDate: Date! @default(expr: "request.time")
}
